### ISSUE TITLE
installation error: sqlite3.DatabaseError: file is not a database

### ISSUE THREAD

**Issue by liaosvcaf** [svcaf/earlyAlertOfLaws#31]
I was following https://github.com/svcaf/earlyAlertOfLaws/blob/master/README.md . 
I got the following error when running reindex.py

```
ubuntu@ip-172-31-24-70:~/earlyAlertOfLaws/webapp$ python3 reindex.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: file is not a database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reindex.py", line 2, in <module>
    from models import Bill
  File "/home/ubuntu/earlyAlertOfLaws/webapp/models.py", line 5, in <module>
    db.Model.metadata.reflect(db.engine)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4228, in reflect
    bind.engine.table_names(schema, connection=conn)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2257, in table_names
    return self.dialect.get_table_names(conn, schema)
  File "<string>", line 2, in get_table_names
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/reflection.py", line 44, in cache
    return fn(self, con, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1593, in get_table_names
    rs = connection.execute(s)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 976, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
    parameters,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) file is not a database
[SQL: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name]
(Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by liaosvcaf** [comment]
@taivy 
The previous one has disappeared. A new error message shows up:

```
python3 reindex.py
Traceback (most recent call last):
  File "reindex.py", line 2, in <module>
    from models import Bill
  File "/home/ubuntu/earlyAlertOfLaws/webapp/models.py", line 51, in <module>
    class Bill(SearchableMixin, db.Model):
  File "/home/ubuntu/earlyAlertOfLaws/webapp/models.py", line 55, in Bill
    __table__ = db.Model.metadata.tables['bills']
KeyError: 'bills'
```

**Comment by liaosvcaf** [comment]
yet a new one after the 2nd error is fixed. 
```
~/earlyAlertOfLaws/webapp$ python3 reindex.py
/home/ubuntu/.local/lib/python3.6/site-packages/sqlalchemy/dialects/sqlite/base.py:1751: SAWarning: Could not instantiate type <class 'sqlalchemy.sql.sqltypes.INTEGER'> with reflected arguments ['25']; using no arguments.
  % (coltype, args)
```

**Comment by liaosvcaf** [comment]
Ok. The last error is a warning. I close this for now.
